/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicM3uRouteImport } from './routes/api/public/m3u'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicM3uRoute = ApiPublicM3uRouteImport.update({
  id: '/api/public/m3u',
  path: '/api/public/m3u',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/m3u': typeof ApiPublicM3uRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/m3u': typeof ApiPublicM3uRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/m3u': typeof ApiPublicM3uRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/m3u'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/m3u'
  id: '__root__' | '/' | '/api/public/m3u'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicM3uRoute: typeof ApiPublicM3uRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/m3u': {
      id: '/api/public/m3u'
      path: '/api/public/m3u'
      fullPath: '/api/public/m3u'
      preLoaderRoute: typeof ApiPublicM3uRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicM3uRoute: ApiPublicM3uRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
